zip -r -j Templates\AbstractBaseClass.zip src\AbstractBaseClass\*.* 
zip -r -j Templates\BaseControl.zip src\BaseControl\*.* 
zip -r -j Templates\BasicReport.zip src\BasicReport\*.* 
zip -r -j Templates\BasicTextIO.zip src\BasicTextIO\*.* 
zip -r -j Templates\BusinessProcess.zip src\BusinessProcess\*.* 
zip -r -j Templates\Entity.zip src\Entity\*.* 
zip -r -j Templates\ReportLayout.zip src\ReportLayout\*.* 
zip -r -j Templates\Type.zip src\Type\*.* 
zip -r -j Templates\UIController.zip src\UIController\*.* 
zip -r -j Templates\WebProcess.zip src\WebProcess\*.* 